name: CI AutoMake

on:
  push:
    branches: [branchAutomake]
  pull_request:
    branches: [branchAutomake]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install build dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y g++ automake autoconf

      - name: Auto generate configure script
        run: |
          autoreconf --install
        
      - name: Run configure script
        run: ./configure
      

      - name: Build with Makefile
        run: make

      - name: Create distribution
        run: make dist

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: suite-dist
          path: suite-*.tar.gz
