name: CI AutoMake

on:
  push:
    branches: [branchAutoTest]
  pull_request:
    branches: [branchAutoTest]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install build dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y g++ automake autoconf libboost-test-dev

      - name: Auto generate configure script
        run: |
          autoreconf --install
        
      - name: Run configure script
        run: ./configure
      

      - name: Build with Makefile
        run: make

      - name: Testing for function
        run: make check

      - name: Upload unit test log1
        uses: actions/upload-artifact@v4
        with:
          name: unit-test
          path: unit-test.log

      - name: Upload unit test log2
        uses: actions/upload-artifact@v4
        with:
          name: test-suite
          path: test-suite.log
