name: CI AutoPackage

on:
  push:
    branches: [branchPackage]
  pull_request:
    branches: [branchPackage]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install build dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y g++ automake autoconf debhelper devscripts

      - name: Auto generate configure script
        run: |
          autoreconf --install
        
      - name: Run configure script
        run: ./configure
      
      - name: Auto Build Debiand Package
        run: |
          dpkg-buildpackage -us -uc

      - name: Build with Makefile
        run: make

  #    - name: Create distribution
  #     run: make dist

      - name: Upload Debian artifact
        uses: actions/upload-artifact@v4
        with:
          name: suite-deb
          path: /home/runner/work/DevOps-lab2/suite_*.deb
